nohup: ignoring input
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on https://127.0.0.1:2000
 * Running on https://216.10.244.243:2000
Press CTRL+C to quit
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
Not Found: /
126.253.166.247 - - [16/Feb/2024 04:55:43] "GET / HTTP/1.1" 404 -
Not Found: /
126.253.166.247 - - [16/Feb/2024 04:56:20] "GET / HTTP/1.1" 404 -
Not Found: /
157.50.32.214 - - [16/Feb/2024 04:58:10] "GET / HTTP/1.1" 404 -
Not Found: /favicon.ico
157.50.32.214 - - [16/Feb/2024 04:58:11] "GET /favicon.ico HTTP/1.1" 404 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/serializers.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/urls.py', reloading
 * Restarting with stat
Performing system checks...

Error occurred during checks: ImportError("cannot import name 'create_dealer' from 'skytron_api.views' (/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py)")


Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
Not Found: /
126.253.166.247 - - [16/Feb/2024 05:30:26] "GET / HTTP/1.1" 404 -
Internal Server Error: /api/dealer/create_dealer/
54.86.50.139 - - [16/Feb/2024 05:31:14] "POST /api/dealer/create_dealer/ HTTP/1.1" 500 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
Internal Server Error: /api/dealer/create_dealer/
54.86.50.139 - - [16/Feb/2024 05:35:00] "POST /api/dealer/create_dealer/ HTTP/1.1" 500 -
Internal Server Error: /api/dealer/create_dealer/
54.86.50.139 - - [16/Feb/2024 05:35:21] "POST /api/dealer/create_dealer/ HTTP/1.1" 500 -
Internal Server Error: /api/dealer/create_dealer/
54.86.50.139 - - [16/Feb/2024 05:35:45] "POST /api/dealer/create_dealer/ HTTP/1.1" 500 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
54.86.50.139 - - [16/Feb/2024 05:37:23] "POST /api/dealer/create_dealer/ HTTP/1.1" 200 -
Method Not Allowed: /api/dealer/filter_dealer/
54.86.50.139 - - [16/Feb/2024 05:39:07] "GET /api/dealer/filter_dealer/ HTTP/1.1" 405 -
54.86.50.139 - - [16/Feb/2024 05:39:36] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 05:41:34] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 05:42:01] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 05:42:10] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
Method Not Allowed: /api/manufacturer/filter_manufacturers/
54.86.50.139 - - [16/Feb/2024 05:43:17] "GET /api/manufacturer/filter_manufacturers/ HTTP/1.1" 405 -
54.86.50.139 - - [16/Feb/2024 05:43:25] "POST /api/manufacturer/filter_manufacturers/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 05:43:38] "POST /api/manufacturer/filter_manufacturers/ HTTP/1.1" 200 -
Internal Server Error: /api/manufacturer/create_manufacturer/
54.86.50.139 - - [16/Feb/2024 05:44:08] "POST /api/manufacturer/create_manufacturer/ HTTP/1.1" 500 -
Internal Server Error: /api/manufacturer/create_manufacturer/
54.86.50.139 - - [16/Feb/2024 05:44:41] "POST /api/manufacturer/create_manufacturer/ HTTP/1.1" 500 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
54.86.50.139 - - [16/Feb/2024 05:48:53] "POST /api/manufacturer/create_manufacturer/ HTTP/1.1" 200 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/serializers.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/urls.py', reloading
 * Restarting with stat
Performing system checks...

Error occurred during checks: TypeError('kwargs argument must be a dict, but got str.')


Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
54.86.50.139 - - [16/Feb/2024 06:07:49] "POST /api/eSimProvider/create_eSimProvider/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/staticfiles/handlers.py", line 80, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/django_extensions/management/commands/runserver_plus.py", line 350, in application
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/django_extensions/management/commands/runserver_plus.py", line 391, in inner_run
    check_errors(self.check)(display_num_errors=self.show_startup_messages)
  File "/usr/local/lib/python3.8/dist-packages/django_extensions/management/commands/runserver_plus.py", line 149, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/html/skytron_backend/Skytronsystem/Skytronsystem/urls.py", line 24, in <module>
    path('api/', include('skytron_api.urls')),  # Include the skytron_api URLs
  File "/usr/local/lib/python3.8/dist-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/html/skytron_backend/Skytronsystem/skytron_api/urls.py", line 66, in <module>
    path('eSimProvider/create_eSimProvider/', create_eSimProvider,'create_eSimProvider'),
  File "/usr/local/lib/python3.8/dist-packages/django/urls/conf.py", line 65, in _path
    raise TypeError(
TypeError: kwargs argument must be a dict, but got str.
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/urls.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
54.86.50.139 - - [16/Feb/2024 06:12:40] "POST /api/eSimProvider/create_eSimProvider/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 06:15:14] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
Forbidden: /api/dealer/filter_dealer/
106.222.198.74 - - [16/Feb/2024 06:38:33] "GET /api/dealer/filter_dealer/ HTTP/1.1" 403 -
Forbidden: /api/dealer/filter_dealer/
106.222.198.74 - - [16/Feb/2024 06:38:55] "GET /api/dealer/filter_dealer/ HTTP/1.1" 403 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/models.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

Error occurred during checks: ImportError("cannot import name 'VehicleOwnerSerializer' from 'skytron_api.serializers' (/var/www/html/skytron_backend/Skytronsystem/skytron_api/serializers.py)")


Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/serializers.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/urls.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
54.86.50.139 - - [16/Feb/2024 07:32:58] "POST /api/VehicleOwner/create_VehicleOwner/ HTTP/1.1" 200 -
Internal Server Error: /api/VehicleOwner/create_VehicleOwner/
54.86.50.139 - - [16/Feb/2024 07:33:25] "POST /api/VehicleOwner/create_VehicleOwner/ HTTP/1.1" 500 -
54.86.50.139 - - [16/Feb/2024 07:36:13] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
Internal Server Error: /api/eSimProvider/filter_eSimProvider/
54.86.50.139 - - [16/Feb/2024 07:36:39] "POST /api/eSimProvider/filter_eSimProvider/ HTTP/1.1" 500 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
Internal Server Error: /api/eSimProvider/filter_eSimProvider/
54.86.50.139 - - [16/Feb/2024 07:42:53] "POST /api/eSimProvider/filter_eSimProvider/ HTTP/1.1" 500 -
Internal Server Error: /api/eSimProvider/filter_eSimProvider/
54.86.50.139 - - [16/Feb/2024 07:43:03] "POST /api/eSimProvider/filter_eSimProvider/ HTTP/1.1" 500 -
54.86.50.139 - - [16/Feb/2024 07:43:37] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
 * Detected change in '/var/www/html/skytron_backend/Skytronsystem/skytron_api/views.py', reloading
 * Restarting with stat
Performing system checks...

System check identified no issues (0 silenced).

Django version 4.2.9, using settings 'Skytronsystem.settings'
Development server is running at https://0.0.0.0:2000/
Using the Werkzeug debugger (https://werkzeug.palletsprojects.com/)
Quit the server with CONTROL-C.
 * Debugger is active!
 * Debugger PIN: 207-926-686
54.86.50.139 - - [16/Feb/2024 07:46:33] "POST /api/dealer/filter_dealer/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 07:46:48] "POST /api/eSimProvider/filter_eSimProvider/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 07:46:55] "POST /api/eSimProvider/filter_eSimProvider/ HTTP/1.1" 200 -
54.86.50.139 - - [16/Feb/2024 07:47:02] "POST /api/eSimProvider/filter_eSimProvider/ HTTP/1.1" 200 -
Not Found: /api/VehicleOwner/VehicleOwner/
54.86.50.139 - - [16/Feb/2024 07:48:02] "POST /api/VehicleOwner/VehicleOwner/ HTTP/1.1" 404 -
54.86.50.139 - - [16/Feb/2024 07:49:24] "POST /api/VehicleOwner/filter_VehicleOwner/ HTTP/1.1" 200 -
